"""add notification_sent_at to capsules

Revision ID: 52b591cd7c55
Revises: 1b086e467457
Create Date: 2026-06-26 18:45:59.593902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b591cd7c55'
down_revision: Union[str, Sequence[str], None] = '1b086e467457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capsules', 'notification_sent_at')
    # ### end Alembic commands ###
