"""initial tables

Revision ID: df0e85fe518a
Revises: 
Create Date: 2026-06-26 17:35:24.619411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0e85fe518a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('capsules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('free', 'ai_assisted', name='capsulemode'), nullable=False),
    sa.Column('status', sa.Enum('locked', 'opened', name='capsulestatus'), nullable=False),
    sa.Column('open_date', sa.Date(), nullable=False),
    sa.Column('notification_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capsules_user_id'), 'capsules', ['user_id'], unique=False)
    op.create_table('capsule_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capsule_id', sa.String(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capsule_answers_capsule_id'), 'capsule_answers', ['capsule_id'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('capsule_id', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capsule_id'], ['capsules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_capsule_id'), 'reflections', ['capsule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reflections_capsule_id'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index(op.f('ix_capsule_answers_capsule_id'), table_name='capsule_answers')
    op.drop_table('capsule_answers')
    op.drop_index(op.f('ix_capsules_user_id'), table_name='capsules')
    op.drop_table('capsules')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
